### ISSUE TITLE
Cannot run this demo

### ISSUE THREAD

**Issue by jiwonyune** [colinskow/tns-image-test#1]
Hi,

I am just trying as it is said on `Readme.md`, but I keep getting this error:

```
Found peer TypeScript 1.8.10
node_modules/reflect-metadata/index.d.ts(20,15): error TS2665: Module augmentation cannot introduce new names in the top level scope.
```

Fixing this problem seems like beyond my capability. Can anyone take a look at this?

FYI,

tns --version 2.4.2
tns-android 2.4.1

Thanks a lot in advance!

**Comment by colinskow** [comment]
It needs some work to upgrade to the latest version of NativeScript. This was done with a prerelease version of Angular 2 so the modules need to be upgraded.

**Comment by jiwonyune** [comment]
@colinskow Thanks a lot for the reply. I am working on something similar to this demo, and if I happen to fix the problem, I'll make another branch.
